# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: SUPER_SECRET_RANDOM_KEY
slack:
  webhook_url: "https://hooks.slack.com/services/the/secret/details"